name: Continuous Integration

on:
  pull_request:
    branches: ['main']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader

      - name: Composer validate
        run: composer validate --strict --no-check-publish

      - name: Composer audit
        run: composer audit

      - name: Lint PHP files
        uses: overtrue/phplint@main
        with:
          path: .
          options: --exclude=vendor
